// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8mBsLNOnKAiq0m-arTQjXrxXV9F66YGQ',
    appId: '1:248952140430:web:a534617a91ed7877274fdf',
    messagingSenderId: '248952140430',
    projectId: 'monastors-ac7fd',
    authDomain: 'monastors-ac7fd.firebaseapp.com',
    storageBucket: 'monastors-ac7fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXxzGH6Y3L-AQxQuWymsWiP0fgDbgLc68',
    appId: '1:248952140430:android:a7f748b150114283274fdf',
    messagingSenderId: '248952140430',
    projectId: 'monastors-ac7fd',
    storageBucket: 'monastors-ac7fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe407pgWX_a5_ivI_B8kC82mewgr2l4Jc',
    appId: '1:248952140430:ios:978e29833d4c3b30274fdf',
    messagingSenderId: '248952140430',
    projectId: 'monastors-ac7fd',
    storageBucket: 'monastors-ac7fd.firebasestorage.app',
    iosBundleId: 'com.example.monastors',
  );

}